### ISSUE TITLE
Plants aren't fractals

### ISSUE THREAD

**Issue by daveloyall** [rue-a/L-Systems-Website#1]
Hello.

When you have a minute, please read the Abstract and Introduction of this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3419012/ .

And this choice line from the Discussion section:

> The elegance of using computerized fractal-forming programs to describe general plant morphology has nothing to do with the actual anatomical structure and the patterns of developmental processes that result in the formation of such plant organs.

We might summarize the whole paper as "plants aren't fractals".

Of course, that doesn't change L-systems at all.  Doesn't change the math or the code at all, I mean.

But perhaps it would be worthwhile to add something to this one line from `README.md`?

> [...] first and foremost, they were developed to model the growth of plants.

Cheers,
--sebboh

**Comment by rue-a** [comment]
Hi sebboh, many thanks for your comment. I just updated the Readme. Feel free to issue a pull request, if I messed something up.

Cheers!
